(()=>{'use strict';const $=s=>document.querySelector(s),C=window.PITCH_CATALOG,changes=window.PITCH_CHANGES;
const labels={all:'전체',story:'발표 구성',interaction:'조작',visual:'시각·연출',pet:'펫의 의미',evidence:'근거',architecture:'기술 구조',delivery:'배포·용량'};
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const thumb=(v,p,c=1)=>`examples/previews/${v}-${p}-${c}.webp`,ver=id=>C.versions.find(v=>v.id===id);
let filter='all',selected=[],blobUrl=null,payloadPromise=null,zipPromise=null;
const loadScript=src=>new Promise((resolve,reject)=>{const s=document.createElement('script');s.src=src;s.onload=resolve;s.onerror=()=>{s.remove();reject(Error('파일을 불러오지 못했습니다: '+src));};document.body.append(s);});
const source=()=>payloadPromise||(payloadPromise=loadScript('gallery/payload.js').then(()=>window.PITCH_SOURCE).catch(e=>{payloadPromise=null;throw e;}));
function preview(file,title){$('#preview-title').textContent=title;$('#preview-frame').src=file;$('#preview-dialog').showModal();}
function previewRef(ref){preview(`${ver(ref.version).file}#${ref.page}/${ref.cue}`,`${ver(ref.version).label} · ${ref.page}장`);}
async function copy(text,button){try{await navigator.clipboard.writeText(text);const old=button.textContent;button.textContent='복사됨 ✓';setTimeout(()=>button.textContent=old,1800);}catch{$('#copy-text').value=text;$('#copy-dialog').showModal();$('#copy-text').focus();$('#copy-text').select();}}
document.querySelectorAll('.dialog-close').forEach(b=>b.onclick=()=>b.closest('dialog').close());
$('#preview-dialog').addEventListener('close',()=>{$('#preview-frame').src='about:blank';if(blobUrl){URL.revokeObjectURL(blobUrl);blobUrl=null;}});
$('#hero-preview').onclick=()=>previewRef({version:'final',page:8,cue:1});
$('#version-grid').innerHTML=C.versions.map((v,i)=>`<article class="version-card"><button class="thumbnail" data-version="${v.id}" aria-label="${v.label} 미리보기"><img loading="lazy" src="${thumb(v.id,i===2?8:1)}" alt="${v.label} 화면"></button><div class="version-info"><span class="tag">${i===2?'FINAL / OPTIMIZED':'CHECKPOINT / 0'+(i+1)}</span><h3>${v.label}</h3><p>${v.description}</p><div class="version-actions"><span>${(v.bytes/1048576).toFixed(1)} MiB · 원본 보존</span><a href="${v.file}" download="AutoPets-${v.id}.html">HTML ↓</a></div></div></article>`).join('');
document.querySelectorAll('[data-version]').forEach(b=>b.onclick=()=>previewRef({version:b.dataset.version,page:1,cue:1}));
$('#filters').innerHTML=Object.entries(labels).map(([k,l])=>`<button data-filter="${k}" class="${k===filter?'active':''}">${l}</button>`).join('');
document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;document.querySelectorAll('[data-filter]').forEach(x=>x.classList.toggle('active',x===b));renderChanges();});
$('#search').oninput=renderChanges;
function renderChanges(){const q=$('#search').value.trim().toLowerCase(),shown=changes.filter(c=>(filter==='all'||c.category===filter)&&(!q||JSON.stringify(c).toLowerCase().includes(q)));$('#change-grid').innerHTML=shown.map(c=>`<button class="change-card" data-case="${c.id}"><span class="tag">${labels[c.category]} / ${c.id.slice(-2)}</span><h3>${c.title}</h3><p>${escape(c.quote)}</p><span class="card-end"><span>요청과 반영 화면</span><b>↗</b></span></button>`).join('')||'<p class="no-results">일치하는 기록이 없습니다.</p>';document.querySelectorAll('[data-case]').forEach(b=>b.onclick=()=>openCase(changes.find(c=>c.id===b.dataset.case)));}
function openCase(c){const figure=(ref,label)=>ref?`<figure><button class="thumbnail" data-ref='${JSON.stringify(ref)}' aria-label="${label} 실제 발표 열기"><img src="${thumb(ref.version,ref.page,ref.cue)}" alt="${label} ${ver(ref.version).label} ${ref.page}장"></button><figcaption>${label} · ${ver(ref.version).label} / ${ref.page}장 ↗</figcaption></figure>`:`<figure><div class="missing">요청 기록 확인<br>당시 화면 없음</div><figcaption>과거 화면을 재구성하지 않았습니다.</figcaption></figure>`;
$('#case-content').innerHTML=`<p class="eyebrow">${labels[c.category]} / ${c.id}</p><h2>${c.title}</h2><div class="case-quote">${escape(c.quote)}</div><p class="case-explanation"><b>요청 원문 발췌</b> · ${c.intent}</p><div class="compare">${figure(c.before,'이전 보관 시점')}${figure(c.after,'반영 화면')}</div><p class="case-explanation">${c.evidence}</p><p class="case-explanation"><b>바뀐 것</b> · ${c.change}<br><b>확인 기준</b> · ${c.acceptance}${c.supersedes.length?'<br><b>대체한 방향</b> · '+c.supersedes.join(', '):''}</p><div class="prompt-box"><span class="tag">REUSABLE PROMPT</span><p>${escape(c.prompt)}</p><div class="case-actions"><button id="copy-prompt" class="primary">재사용 프롬프트 복사</button><button id="copy-original" class="secondary">요청 원문 복사</button></div></div>`;
$('#copy-prompt').onclick=e=>copy(c.prompt,e.target);$('#copy-original').onclick=e=>copy(c.quote,e.target);$('#case-content').querySelectorAll('[data-ref]').forEach(b=>b.onclick=()=>previewRef(JSON.parse(b.dataset.ref)));$('#case-dialog').showModal();}
const units=C.scenes.filter(s=>!s.group||s.id==='closing-position');
function sceneLabel(id){const s=C.scenes.find(s=>s.id===id);return s.group?'마지막 3장 · 역할에서 작품의 목적으로':s.title;}
function renderScenes(){$('#scene-grid').innerHTML=units.map(s=>`<article class="scene-card ${selected.includes(s.id)?'selected':''}"><button class="thumbnail" data-scene-preview="${s.id}" aria-label="${s.title} 미리보기"><img loading="lazy" src="${thumb('final',s.originalPage,s.id==='meaning'?4:1)}" alt="${s.title}"></button><div class="scene-info"><span class="tag">${String(s.originalPage).padStart(2,'0')}${s.group?'–20 / 연속 장면':` / ${s.steps+1}개 화면 상태`}</span><h3>${sceneLabel(s.id)}</h3><div class="scene-actions"><button class="text-button" data-scene-preview="${s.id}">실제 화면 ↗</button><button class="scene-select" data-select="${s.id}" aria-pressed="${selected.includes(s.id)}">${selected.includes(s.id)?'선택됨 ✓':'담기 +'}</button></div></div></article>`).join('');document.querySelectorAll('[data-scene-preview]').forEach(b=>b.onclick=()=>{const s=C.scenes.find(s=>s.id===b.dataset.scenePreview);previewRef({version:'final',page:s.originalPage,cue:1});});document.querySelectorAll('[data-select]').forEach(b=>b.onclick=()=>{const id=b.dataset.select;selected=selected.includes(id)?selected.filter(x=>x!==id):[...selected,id];renderScenes();renderSelection();});}
function renderSelection(){$('#selection-count').textContent=selected.reduce((n,id)=>n+(id==='closing-position'?3:1),0);$('#selection-empty').hidden=!!selected.length;$('#selection-list').innerHTML=selected.map((id,i)=>`<li><span>${escape(sceneLabel(id))}</span><button data-move="${i},-1" ${i===0?'disabled':''} aria-label="${escape(sceneLabel(id))} 위로">↑</button><button data-move="${i},1" ${i===selected.length-1?'disabled':''} aria-label="${escape(sceneLabel(id))} 아래로">↓</button><button data-remove="${id}" aria-label="${escape(sceneLabel(id))} 제거">×</button></li>`).join('');['export-html','export-zip','preview-selection'].forEach(id=>$('#'+id).disabled=!selected.length);document.querySelectorAll('[data-move]').forEach(b=>b.onclick=()=>{const[i,d]=b.dataset.move.split(',').map(Number);[selected[i],selected[i+d]]=[selected[i+d],selected[i]];renderSelection();});document.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{selected=selected.filter(x=>x!==b.dataset.remove);renderSelection();renderScenes();});}
function download(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);}
const filename=()=>($('#deck-title').value.trim()||'presentation').replace(/[<>:"/\\|?*\x00-\x1f]/g,'-');
async function getDeck(){$('#export-status').textContent='선택한 화면과 필요한 자산을 준비하고 있어요…';const result=PitchCompose.compose(selected,await source(),$('#deck-title').value);$('#export-status').textContent=`${result.ids.length}장 · ${(new Blob([result.standalone]).size/1048576).toFixed(1)} MiB · 오프라인 HTML`;return result;}
$('#export-html').onclick=async()=>{try{const d=await getDeck();download(new Blob([d.standalone],{type:'text/html;charset=utf-8'}),filename()+'.html');}catch(e){$('#export-status').textContent=e.message;}};
$('#preview-selection').onclick=async()=>{try{const d=await getDeck();blobUrl=URL.createObjectURL(new Blob([d.standalone],{type:'text/html;charset=utf-8'}));preview(blobUrl,$('#deck-title').value);}catch(e){$('#export-status').textContent=e.message;}};
$('#export-zip').onclick=async()=>{try{const d=await getDeck();await(zipPromise||(zipPromise=loadScript('gallery/vendor/jszip.min.js').catch(e=>{zipPromise=null;throw e;})));const zip=new JSZip();zip.file('index.html',d.html);zip.file('styles.css',d.css);zip.file('runtime.js',d.runtime);zip.file('presentation.html',d.standalone);zip.file('scene-manifest.json',JSON.stringify(d.scenes,null,2));for(const[key,a]of Object.entries(d.assets))zip.file(key,a.base64,{base64:true});zip.file('build.mjs',window.PITCH_SOURCE.buildScript);zip.file('README.md','# 선택한 HTML 발표\n\nindex.html에서 본문, styles.css에서 스타일, runtime.js에서 동작을 수정합니다. Node.js로 node build.mjs를 실행하면 presentation.html을 다시 생성합니다. 발표할 때는 presentation.html만 옮기세요.\n\n장면 목록과 내부 단계는 scene-manifest.json에 기록되어 있습니다. 실제 작품 사례·로고의 출처는 SOURCES.md를 확인하세요.\n');zip.file('SOURCES.md',window.PITCH_SOURCE.sources);download(await zip.generateAsync({type:'blob',compression:'DEFLATE',compressionOptions:{level:6}}),filename()+'-source.zip');$('#export-status').textContent+=' · 편집 ZIP 준비 완료';}catch(e){$('#export-status').textContent=e.message;}};
renderChanges();renderScenes();renderSelection();
})();
