import fs from'node:fs';import path from'node:path';import{createRequire}from'node:module';import{spawnSync}from'node:child_process';import crypto from'node:crypto';import{root}from'./source.mjs';
let JSZip;try{JSZip=(await import('jszip')).default;}catch{JSZip=createRequire(path.join(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES,'package.json'))('jszip');}
const out=path.join(root,'artifacts');fs.mkdirSync(out,{recursive:true});
function files(dir){return fs.readdirSync(dir,{withFileTypes:true}).flatMap(e=>e.isDirectory()?files(path.join(dir,e.name)):[path.join(dir,e.name)]);}
async function save(zip,name){fs.writeFileSync(path.join(out,name),await zip.generateAsync({type:'nodebuffer',compression:'DEFLATE',compressionOptions:{level:6}}));}
const originals=JSON.parse(fs.readFileSync(path.join(root,'examples/versions/manifest.json')));for(const v of originals)fs.copyFileSync(path.join(root,v.file),path.join(out,'AutoPets-'+v.id+'.html'));
const final=new JSZip();for(const file of files(path.join(root,'examples/final-source')))final.file(path.relative(path.join(root,'examples/final-source'),file).replaceAll('\\','/'),fs.readFileSync(file));
for(const file of files(path.join(root,'assets/templates/autopets/assets')))final.file('assets/'+path.basename(file),fs.readFileSync(file));
for(const file of files(path.join(root,'examples/autopets-docs')))final.file(path.basename(file),fs.readFileSync(file));final.file('AutoPets_5분발표.html',fs.readFileSync(path.join(root,'examples/versions/final.html')));await save(final,'AutoPets-final-editable.zip');
const skill=new JSZip(),include=['SKILL.md','agents','scripts','references','assets','gallery/compose.js','data','THIRD_PARTY.md','examples/autopets-docs','package.json','package-lock.json','requirements.txt'];
for(const name of include){const p=path.join(root,name);for(const file of fs.statSync(p).isDirectory()?files(p):[p])skill.file('html-pitch-artifacts-v2/'+path.relative(root,file).replaceAll('\\','/'),fs.readFileSync(file));}await save(skill,'html-pitch-artifacts-v2-skill.zip');
const gallery=new JSZip();for(const name of ['index.html','gallery','examples','references','reports','SKILL.md','THIRD_PARTY.md']){const p=path.join(root,name);for(const file of fs.statSync(p).isDirectory()?files(p):[p])gallery.file('html-pitch-gallery/'+path.relative(root,file).replaceAll('\\','/'),fs.readFileSync(file));}await save(gallery,'html-pitch-gallery-offline.zip');
// Independently unpack and rebuild the browser-generated editable ZIP, then compare bytes.
const downloaded=path.join(root,'.build/qa/gallery-source.zip');let rebuild={status:'not-run',reason:'Run npm run qa first'};
if(fs.existsSync(downloaded)){const z=await JSZip.loadAsync(fs.readFileSync(downloaded)),dir=path.join(root,'.build/rebuild-selected');fs.mkdirSync(dir,{recursive:true});for(const[name,item]of Object.entries(z.files)){const target=path.resolve(dir,name);if(!target.startsWith(path.resolve(dir)+path.sep))throw Error('Unsafe ZIP path');if(!item.dir){fs.mkdirSync(path.dirname(target),{recursive:true});fs.writeFileSync(target,await item.async('nodebuffer'));}}const before=fs.readFileSync(path.join(dir,'presentation.html'));const p=spawnSync(process.execPath,[path.join(dir,'build.mjs')],{encoding:'utf8'});if(p.status!==0)throw Error(p.stderr);const after=fs.readFileSync(path.join(dir,'presentation.html'));if(!before.equals(after))throw Error('Selected ZIP rebuilt HTML differs');rebuild={status:'passed',bytes:after.length,sha256:crypto.createHash('sha256').update(after).digest('hex')};}
const finalDir=path.join(root,'.build/rebuild-final');fs.mkdirSync(finalDir,{recursive:true});for(const[name,item]of Object.entries(final.files))if(!item.dir){const target=path.join(finalDir,name);fs.mkdirSync(path.dirname(target),{recursive:true});fs.writeFileSync(target,await item.async('nodebuffer'));}const p=spawnSync(process.execPath,[path.join(finalDir,'build.mjs')],{encoding:'utf8'});if(p.status!==0)throw Error(p.stderr);const rebuilt=fs.readFileSync(path.join(finalDir,'AutoPets_5분발표.html'));if(crypto.createHash('sha256').update(rebuilt).digest('hex')!==originals.find(v=>v.id==='final').sha256)throw Error('Final source ZIP does not reproduce archive');
const artifacts=files(out).map(file=>({file:path.basename(file),bytes:fs.statSync(file).size,sha256:crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex')}));fs.writeFileSync(path.join(root,'reports/packages.json'),JSON.stringify({selectedRebuild:rebuild,finalRebuild:{status:'passed',sha256:originals.find(v=>v.id==='final').sha256},artifacts},null,2));console.log(JSON.stringify({selectedRebuild:rebuild.status,finalRebuild:'passed',artifacts:artifacts.map(({file,bytes})=>({file,bytes}))}));
