import fs from'node:fs';import path from'node:path';import{pathToFileURL}from'node:url';import{createRequire}from'node:module';import crypto from'node:crypto';import{getSource,root}from'./source.mjs';import'../gallery/compose.js';
const mod=async name=>{try{return await import(name);}catch{const value=createRequire(path.join(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES,'package.json'))(name);return{...value,default:value};}};
const {chromium}=await mod('playwright'),sharp=(await mod('sharp')).default;
const browser=await chromium.launch({headless:true,...(process.env.CHROMIUM_EXECUTABLE_PATH?{executablePath:process.env.CHROMIUM_EXECUTABLE_PATH}:{})});
const work=path.join(root,'.build/qa');fs.mkdirSync(work,{recursive:true});fs.mkdirSync(path.join(root,'examples/previews'),{recursive:true});fs.mkdirSync(path.join(root,'reports'),{recursive:true});
const source=getSource(),versions=JSON.parse(fs.readFileSync(path.join(root,'examples/versions/manifest.json'))),cases=JSON.parse(fs.readFileSync(path.join(root,'data/changes.json')));
const report={date:new Date().toISOString(),browser:browser.version(),screenshots:[],geometry:[],extractionComparisons:[],interaction:[],offline:[],images:[],warnings:[],errors:[]};
const hash=b=>crypto.createHash('sha256').update(b).digest('hex');
const ctx=await browser.newContext({viewport:{width:1280,height:720},reducedMotion:'reduce'});ctx.setDefaultTimeout(10000);
await ctx.route(/^https?:/,r=>r.abort());const page=await ctx.newPage();page.on('pageerror',e=>report.errors.push(e.message));
async function load(file){await page.goto(pathToFileURL(file).href);await page.evaluate(()=>document.fonts.ready);await page.evaluate(()=>Promise.all([...document.images].map(i=>{i.loading='eager';return i.decode().catch(()=>{});})));}
async function cue(p,c){await page.evaluate(({p,c})=>{if(window.AutoPetsDeck)window.AutoPetsDeck.go(p-1,c-1);else location.hash=`#${p}/${c}`;},{p,c});await page.waitForTimeout(30);}
async function snap(v,p,c,size){const n=`${v}-${p}-${c}`,file=path.join(work,`${n}-${size.width}.png`);const reuse=process.argv.includes('--reuse-captures')&&fs.existsSync(file);if(!reuse){await page.screenshot({path:file});if(size.width===1280)await sharp(file).resize(640,360).webp({quality:82}).toFile(path.join(root,'examples/previews',n+'.webp'));}report.screenshots.push({version:v,page:p,cue:c,width:size.width,height:size.height,reusedCapture:reuse,file:path.relative(root,file).replaceAll('\\','/')});if(v==='final'){const issues=await page.locator('.is-active h1,.is-active h2').evaluateAll(nodes=>nodes.filter(n=>!n.closest('[aria-hidden="true"]')).flatMap(n=>{const r=n.getBoundingClientRect(),s=getComputedStyle(n);if(s.display==='none'||s.visibility==='hidden'||!r.width||!r.height)return[];return r.left< -2||r.top< -2||r.right>innerWidth+2||r.bottom>innerHeight+2||n.scrollWidth>n.clientWidth+3?[{text:n.textContent.trim().slice(0,80),bounds:[r.x,r.y,r.width,r.height]}]:[];}));report.geometry.push({page:p,cue:c,width:size.width,headingIssues:issues});if(issues.length)report.errors.push(`Heading overflow ${v}/${p}/${c}/${size.width}`);}}
for(const v of versions){await load(path.join(root,v.file));const count=await page.locator('.slide').count();if(count!==v.pages)throw Error('Wrong archive page count');const broken=await page.locator('img').evaluateAll(imgs=>imgs.filter(i=>!i.complete||!i.naturalWidth).map(i=>i.alt));if(broken.length)report.errors.push(`${v.id}: broken images ${broken}`);report.offline.push({id:v.id,network:'HTTP(S) blocked',brokenImages:broken.length,hashMatches:hash(fs.readFileSync(path.join(root,v.file)))===v.sha256});
const wanted=new Map();for(let p=1;p<=v.pages;p++)wanted.set(`${p}-1`,[p,1]);for(const c of cases)for(const ref of [c.before,c.after])if(ref?.version===v.id)wanted.set(`${ref.page}-${ref.cue}`,[ref.page,ref.cue]);if(v.id==='final')for(const s of source.scenes)for(let c=1;c<=s.steps+1;c++)wanted.set(`${s.originalPage}-${c}`,[s.originalPage,c]);
for(const size of(v.id==='final'?[{width:1280,height:720},{width:1920,height:1080}]:[{width:1280,height:720}])){await page.setViewportSize(size);for(const[p,c]of wanted.values()){await cue(p,c);await snap(v.id,p,c,size);}}
console.log('Captured '+v.id);}
await page.setViewportSize({width:1280,height:720});
for(const s of source.scenes.filter(s=>!s.group||s.id==='closing-position')){const d=PitchCompose.compose([s.id],source),file=path.join(work,'single-'+s.id+'.html');fs.writeFileSync(file,d.standalone);await load(file);const list=await page.evaluate(()=>PitchDeck.getScenes());if(list.length!==d.ids.length)throw Error('Single scene extraction failed');for(let i=0;i<list.length;i++)for(let c=0;c<=list[i].steps;c++){await page.evaluate(({i,c})=>PitchDeck.go(i,c),{i,c});const st=await page.evaluate(()=>PitchDeck.getState());if(st.sceneId!==list[i].id||st.cue!==c)throw Error('Direct cue mismatch');const shot=await page.screenshot(),original=source.scenes.find(x=>x.id===list[i].id),a=await sharp(shot).removeAlpha().raw().toBuffer(),b=await sharp(path.join(work,`final-${original.originalPage}-${c+1}-1280.png`)).removeAlpha().raw().toBuffer();let error=0;for(let p=0;p<a.length;p++)error+=Math.abs(a[p]-b[p]);const difference=error/(a.length*255);report.extractionComparisons.push({scene:list[i].id,cue:c,meanPixelDifference:difference});if(difference>.02)report.warnings.push(`Extracted visual differs: ${list[i].id}/${c}: ${(difference*100).toFixed(2)}%`);}report.interaction.push({test:'single-scene',scene:s.id,pages:list.length,pass:true});}
const selection=['roles','gurumi-intro','ecosystem','meaning','demo','closing-position','cover'],mixed=PitchCompose.compose(selection,source);const mixedFile=path.join(work,'mixed.html');fs.writeFileSync(mixedFile,mixed.standalone);await load(mixedFile);
const mixedList=await page.evaluate(()=>PitchDeck.getScenes());if(mixedList.at(-1).id!=='cover')throw Error('Selection order lost');
// Check four distinct click targets against a scene with a cue.
for(const selector of ['.roles h2','.roles img','.roles .role-card','#deck']){await page.evaluate(()=>PitchDeck.go(0,0));const loc=page.locator(selector).first();if(await loc.count()){await loc.click({force:true,position:selector==='#deck'?{x:3,y:3}:undefined});const st=await page.evaluate(()=>PitchDeck.getState());if(st.cue!==1)throw Error('Click target failed '+selector);report.interaction.push({test:'click-target',selector,pass:true});}}
await page.emulateMedia({reducedMotion:'no-preference'});await page.evaluate(()=>{document.body.classList.remove('reduced-motion');PitchDeck.go(0,0);PitchDeck.next();PitchDeck.next();});let st=await page.evaluate(()=>PitchDeck.getState());if(st.cue!==1||!st.busy)throw Error('Duplicate click lock failed');await page.keyboard.press('ArrowLeft');await page.waitForTimeout(3100);st=await page.evaluate(()=>PitchDeck.getState());if(st.cue!==0||st.rolePhase!==0)throw Error('Cancelled timers changed prior state');report.interaction.push({test:'duplicate-next-and-previous-cancellation',pass:true});
await page.evaluate(()=>PitchDeck.next());await page.emulateMedia({reducedMotion:'reduce'});await page.waitForTimeout(250);st=await page.evaluate(()=>PitchDeck.getState());if(st.rolePhase!==3||st.busy)throw Error('Reduced motion did not settle: '+JSON.stringify(st));report.interaction.push({test:'reduced-motion-current-cue',pass:true});console.log('Interaction checks passed');
await page.evaluate(()=>PitchDeck.go(PitchDeck.getScenes().findIndex(s=>s.id==='feedback'),2));await page.keyboard.press('ArrowRight');await page.waitForTimeout(50);if((await page.evaluate(()=>PitchDeck.getState())).sceneId!=='cover')throw Error('Shared canvas failed with following scene');report.interaction.push({test:'closing-group-reorder-and-following-scene',pass:true});
// Gallery opens as a file without fetch/CDN; exports a real download.
await load(path.join(root,'index.html'));await page.locator('[data-case="change-15"]').click();if(!await page.locator('#copy-prompt').isVisible())throw Error('Missing prompt copy');await page.evaluate(()=>Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:()=>Promise.reject(Error('QA: clipboard denied'))}}));await page.locator('#copy-prompt').click();if(!await page.locator('#copy-dialog').isVisible()||!(await page.locator('#copy-text').inputValue()).includes('집중 게이지'))throw Error('Clipboard fallback missing');await page.locator('#copy-dialog .dialog-close').click();await page.locator('#case-dialog .dialog-close').click();report.interaction.push({test:'clipboard-denial-manual-copy-fallback',pass:true});
await page.locator('[data-select="gurumi-intro"]').click();await page.locator('[data-select="closing-position"]').click();await page.locator('[data-select="cover"]').click();await page.locator('[data-move="2,-1"]').click();
const dlPromise=page.waitForEvent('download');await page.locator('#export-html').click();const dl=await dlPromise;await dl.saveAs(path.join(work,'gallery-download.html'));
const zipPromise=page.waitForEvent('download');await page.locator('#export-zip').click();const zip=await zipPromise;await zip.saveAs(path.join(work,'gallery-source.zip'));report.interaction.push({test:'file-gallery-copy-ui-select-reorder-html-zip',pass:true});
await page.screenshot({path:path.join(work,'gallery-desktop.png'),fullPage:true});await page.setViewportSize({width:390,height:844});await page.screenshot({path:path.join(work,'gallery-mobile.png'),fullPage:true});if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1))report.errors.push('Gallery mobile horizontal overflow');
await load(path.join(work,'gallery-download.html'));const exported=await page.evaluate(()=>PitchDeck.getScenes());if(exported.length!==5||exported[1].id!=='cover')throw Error('Gallery export selection order incorrect');report.offline.push({id:'gallery-selected-html',network:'HTTP(S) blocked',pages:exported.length,pass:true});
// File sizes, actual decoding and duplicate embedded byte costs.
for(const[name,a]of Object.entries(source.assets)){const b=Buffer.from(a.base64,'base64');try{let meta;if(a.mime==='image/x-icon'){if(b.readUInt32LE(0)!==65536)throw Error('Invalid ICO header');meta={format:'ico',width:b[6]||256,height:b[7]||256};}else meta=await sharp(b).metadata();report.images.push({file:name,bytes:b.length,width:meta.width,height:meta.height,format:meta.format,mime:a.mime,sha256:hash(b)});}catch(e){report.errors.push('Image decode '+name+': '+e.message);}}
const raw=fs.readFileSync(path.join(root,'examples/versions/final.html'),'utf8'),embedded=[...raw.matchAll(/data:image\/[^;]+;base64,([A-Za-z0-9+/=]+)/g)].map(x=>x[1]);const total=embedded.reduce((n,x)=>n+x.length,0),unique=[...new Set(embedded)].reduce((n,x)=>n+x.length,0);
const sizes={htmlBytes:Buffer.byteLength(raw),htmlMiB:Buffer.byteLength(raw)/1048576,targetMiB:15,reviewThresholdMiB:20,embeddedOccurrences:embedded.length,uniqueEmbeddedImages:new Set(embedded).size,embeddedBase64Bytes:total,repeatedBase64Bytes:total-unique,images:report.images,largestAssets:[...report.images].sort((a,b)=>b.bytes-a.bytes).slice(0,8)};
fs.writeFileSync(path.join(root,'reports/size-report.json'),JSON.stringify(sizes,null,2));
const files=source.scenes.map(s=>({file:s.file,bytes:Buffer.byteLength(s.html)})),allBytes=Buffer.byteLength(source.css+source.runtime+source.scenes.map(s=>s.html).join('')),mapBytes=Buffer.byteLength(JSON.stringify(source.scenes.map(({html,...s})=>s)));
fs.writeFileSync(path.join(root,'reports/context-scope.json'),JSON.stringify({measurement:'UTF-8 source bytes, not billed tokens or a model execution benchmark',fullEditableSourceBytes:allBytes,standaloneBytes:Buffer.byteLength(raw),tasks:[{task:'문구 수정',scopedBytes:mapBytes+files.find(f=>f.file.includes('cover')).bytes},{task:'사진 교체',scopedBytes:mapBytes+files.find(f=>f.file.includes('gurumi-intro')).bytes},{task:'새 장면 추가',scopedBytes:mapBytes+files.find(f=>f.file.includes('cover')).bytes+Buffer.byteLength(source.runtime)},{task:'장면 재조합',scopedBytes:mapBytes}],actualTokenUsage:null},null,2));
report.status=report.errors.length?'failed':'passed';report.limitations=['Chromium 기반 자동 검사이며 모든 OS·브라우저 실기 검수가 아닙니다.','자동 캡처만으로 의미·미적 품질을 판정하지 않습니다. 수동 확인 결과는 summary.md에 기록합니다.','시스템 폰트가 다른 PC에서는 글꼴이 달라질 수 있습니다.'];fs.writeFileSync(path.join(root,'reports/qa.json'),JSON.stringify(report,null,2));
await browser.close();console.log(JSON.stringify({status:report.status,captures:report.screenshots.length,interactions:report.interaction.length,errors:report.errors}));if(report.errors.length)process.exitCode=1;
